# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/selector/vivado_design/selector/selector.srcs/sources_1/ip/selector_0/selector_0.xci
# IP: The module: 'selector_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/selector/vivado_design/selector/selector.srcs/sources_1/ip/selector_0/constraints/selector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selector_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/selector/vivado_design/selector/selector.srcs/sources_1/ip/selector_0/selector_0.xci
# IP: The module: 'selector_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/selector/vivado_design/selector/selector.srcs/sources_1/ip/selector_0/constraints/selector_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'selector_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
