// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ula_new_opUla_HH_
#define _ula_new_opUla_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct ula_new_opUla : public sc_module {
    // Port declarations 7
    sc_in< sc_logic > A;
    sc_in< sc_logic > B;
    sc_in< sc_lv<2> > op;
    sc_out< sc_logic > C;
    sc_out< sc_logic > C_ap_vld;
    sc_out< sc_logic > carryOut;
    sc_out< sc_logic > carryOut_ap_vld;


    // Module declarations
    ula_new_opUla(sc_module_name name);
    SC_HAS_PROCESS(ula_new_opUla);

    ~ula_new_opUla();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<1> > aux_fu_150_p2;
    sc_signal< sc_lv<1> > ap_phi_mux_v_phi_fu_101_p14;
    sc_signal< sc_lv<2> > val_V_read_fu_66_p2;
    sc_signal< sc_lv<1> > grp_read_fu_72_p2;
    sc_signal< sc_lv<1> > ap_phi_mux_v_1_phi_fu_126_p14;
    sc_signal< sc_lv<1> > aux_fu_150_p0;
    sc_signal< sc_lv<1> > aux_fu_150_p1;
    static const bool ap_const_boolean_1;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_3;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_C();
    void thread_C_ap_vld();
    void thread_ap_phi_mux_v_1_phi_fu_126_p14();
    void thread_ap_phi_mux_v_phi_fu_101_p14();
    void thread_aux_fu_150_p0();
    void thread_aux_fu_150_p1();
    void thread_aux_fu_150_p2();
    void thread_carryOut();
    void thread_carryOut_ap_vld();
    void thread_grp_read_fu_72_p2();
    void thread_val_V_read_fu_66_p2();
};

}

using namespace ap_rtl;

#endif
