# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/translator/vivado_design/translator/translator.srcs/sources_1/ip/translator_0/translator_0.xci
# IP: The module: 'translator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/translator/vivado_design/translator/translator.srcs/sources_1/ip/translator_0/constraints/translator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'translator_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/translator/vivado_design/translator/translator.srcs/sources_1/ip/translator_0/translator_0.xci
# IP: The module: 'translator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alexandroni/Dropbox/TCC-JOAO-PEDRO/Vivado/final/examples/display/translator/vivado_design/translator/translator.srcs/sources_1/ip/translator_0/constraints/translator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'translator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
