// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _ula_new_opUla_HH_
#define _ula_new_opUla_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "ula_new_mul_mul_1bkb.h"

namespace ap_rtl {

struct ula_new_opUla : public sc_module {
    // Port declarations 5
    sc_in< sc_lv<16> > A;
    sc_in< sc_lv<16> > B;
    sc_in< sc_lv<3> > op;
    sc_out< sc_lv<16> > C;
    sc_out< sc_logic > C_ap_vld;


    // Module declarations
    ula_new_opUla(sc_module_name name);
    SC_HAS_PROCESS(ula_new_opUla);

    ~ula_new_opUla();

    sc_trace_file* mVcdFile;

    ula_new_mul_mul_1bkb<1,1,16,16,16>* ula_new_mul_mul_1bkb_U1;
    sc_signal< sc_lv<16> > aux_V_3_fu_104_p2;
    sc_signal< sc_lv<16> > ap_phi_mux_v_V_phi_fu_88_p12;
    sc_signal< sc_lv<3> > val_V_read_fu_60_p2;
    sc_signal< sc_lv<16> > p_s_fu_117_p1;
    sc_signal< sc_lv<16> > aux_V_2_fu_136_p2;
    sc_signal< sc_lv<16> > aux_V_1_fu_122_p2;
    sc_signal< sc_lv<16> > aux_V_fu_129_p2;
    sc_signal< sc_lv<1> > tmp_2_fu_111_p2;
    static const bool ap_const_boolean_1;
    static const sc_lv<3> ap_const_lv3_5;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_3;
    static const sc_lv<3> ap_const_lv3_2;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_logic ap_const_logic_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_C();
    void thread_C_ap_vld();
    void thread_ap_phi_mux_v_V_phi_fu_88_p12();
    void thread_aux_V_1_fu_122_p2();
    void thread_aux_V_3_fu_104_p2();
    void thread_aux_V_fu_129_p2();
    void thread_p_s_fu_117_p1();
    void thread_tmp_2_fu_111_p2();
    void thread_val_V_read_fu_60_p2();
};

}

using namespace ap_rtl;

#endif
