// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "translator_transform.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic translator_transform::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic translator_transform::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> translator_transform::ap_ST_fsm_state1 = "1";
const sc_lv<15> translator_transform::ap_ST_fsm_state2 = "10";
const sc_lv<15> translator_transform::ap_ST_fsm_state3 = "100";
const sc_lv<15> translator_transform::ap_ST_fsm_state4 = "1000";
const sc_lv<15> translator_transform::ap_ST_fsm_state5 = "10000";
const sc_lv<15> translator_transform::ap_ST_fsm_state6 = "100000";
const sc_lv<15> translator_transform::ap_ST_fsm_state7 = "1000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state8 = "10000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state9 = "100000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state10 = "1000000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state11 = "10000000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state12 = "100000000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<15> translator_transform::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<32> translator_transform::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> translator_transform::ap_const_lv32_2 = "10";
const sc_lv<32> translator_transform::ap_const_lv32_C = "1100";
const sc_lv<7> translator_transform::ap_const_lv7_7F = "1111111";
const sc_lv<32> translator_transform::ap_const_lv32_D = "1101";
const sc_lv<4> translator_transform::ap_const_lv4_D = "1101";
const sc_lv<4> translator_transform::ap_const_lv4_0 = "0000";
const sc_lv<4> translator_transform::ap_const_lv4_1 = "1";
const sc_lv<4> translator_transform::ap_const_lv4_2 = "10";
const sc_lv<4> translator_transform::ap_const_lv4_3 = "11";
const sc_lv<4> translator_transform::ap_const_lv4_4 = "100";
const sc_lv<4> translator_transform::ap_const_lv4_5 = "101";
const sc_lv<4> translator_transform::ap_const_lv4_6 = "110";
const sc_lv<4> translator_transform::ap_const_lv4_7 = "111";
const sc_lv<4> translator_transform::ap_const_lv4_8 = "1000";
const sc_lv<4> translator_transform::ap_const_lv4_9 = "1001";
const sc_lv<7> translator_transform::ap_const_lv7_4 = "100";
const sc_lv<7> translator_transform::ap_const_lv7_0 = "0000000";
const sc_lv<7> translator_transform::ap_const_lv7_F = "1111";
const sc_lv<7> translator_transform::ap_const_lv7_20 = "100000";
const sc_lv<7> translator_transform::ap_const_lv7_24 = "100100";
const sc_lv<7> translator_transform::ap_const_lv7_4C = "1001100";
const sc_lv<7> translator_transform::ap_const_lv7_6 = "110";
const sc_lv<7> translator_transform::ap_const_lv7_12 = "10010";
const sc_lv<7> translator_transform::ap_const_lv7_4F = "1001111";
const sc_lv<7> translator_transform::ap_const_lv7_1 = "1";
const sc_lv<4> translator_transform::ap_const_lv4_B = "1011";
const sc_lv<5> translator_transform::ap_const_lv5_0 = "00000";
const sc_lv<5> translator_transform::ap_const_lv5_1 = "1";
const sc_lv<5> translator_transform::ap_const_lv5_2 = "10";
const sc_lv<5> translator_transform::ap_const_lv5_3 = "11";
const sc_lv<5> translator_transform::ap_const_lv5_4 = "100";
const sc_lv<5> translator_transform::ap_const_lv5_5 = "101";
const sc_lv<5> translator_transform::ap_const_lv5_6 = "110";
const sc_lv<5> translator_transform::ap_const_lv5_7 = "111";
const sc_lv<5> translator_transform::ap_const_lv5_8 = "1000";
const sc_lv<5> translator_transform::ap_const_lv5_9 = "1001";
const sc_lv<64> translator_transform::ap_const_lv64_2 = "10";
const sc_lv<64> translator_transform::ap_const_lv64_3 = "11";
const sc_lv<64> translator_transform::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> translator_transform::ap_const_lv64_1 = "1";
const sc_lv<4> translator_transform::ap_const_lv4_E = "1110";
const sc_lv<32> translator_transform::ap_const_lv32_E = "1110";
const sc_lv<10> translator_transform::ap_const_lv10_A = "1010";
const sc_lv<32> translator_transform::ap_const_lv32_14 = "10100";
const sc_lv<32> translator_transform::ap_const_lv32_11 = "10001";
const sc_lv<10> translator_transform::ap_const_lv10_3E8 = "1111101000";
const sc_lv<7> translator_transform::ap_const_lv7_A = "1010";
const sc_lv<32> translator_transform::ap_const_lv32_3 = "11";
const sc_lv<4> translator_transform::ap_const_lv4_A = "1010";
const sc_lv<1> translator_transform::ap_const_lv1_1 = "1";
const sc_lv<32> translator_transform::ap_const_lv32_1 = "1";
const sc_lv<32> translator_transform::ap_const_lv32_4F = "1001111";
const sc_lv<22> translator_transform::ap_const_lv22_667 = "11001100111";
const sc_lv<22> translator_transform::ap_const_lv22_51F = "10100011111";
const bool translator_transform::ap_const_boolean_1 = true;

translator_transform::translator_transform(sc_module_name name) : sc_module(name), mVcdFile(0) {
    translator_urem_1bkb_U1 = new translator_urem_1bkb<1,14,10,5,10>("translator_urem_1bkb_U1");
    translator_urem_1bkb_U1->clk(ap_clk);
    translator_urem_1bkb_U1->reset(ap_rst);
    translator_urem_1bkb_U1->start(grp_fu_356_ap_start);
    translator_urem_1bkb_U1->done(grp_fu_356_ap_done);
    translator_urem_1bkb_U1->din0(number);
    translator_urem_1bkb_U1->din1(grp_fu_356_p1);
    translator_urem_1bkb_U1->ce(ap_var_for_const0);
    translator_urem_1bkb_U1->dout(grp_fu_356_p2);
    translator_urem_7cud_U2 = new translator_urem_7cud<1,11,7,5,7>("translator_urem_7cud_U2");
    translator_urem_7cud_U2->clk(ap_clk);
    translator_urem_7cud_U2->reset(ap_rst);
    translator_urem_7cud_U2->start(grp_fu_388_ap_start);
    translator_urem_7cud_U2->done(grp_fu_388_ap_done);
    translator_urem_7cud_U2->din0(div_cast_reg_497);
    translator_urem_7cud_U2->din1(grp_fu_388_p1);
    translator_urem_7cud_U2->ce(ap_var_for_const0);
    translator_urem_7cud_U2->dout(grp_fu_388_p2);
    translator_mul_mudEe_U3 = new translator_mul_mudEe<1,1,12,10,22>("translator_mul_mudEe_U3");
    translator_mul_mudEe_U3->din0(mul2_fu_476_p0);
    translator_mul_mudEe_U3->din1(mul2_fu_476_p1);
    translator_mul_mudEe_U3->dout(mul2_fu_476_p2);
    translator_mul_mudEe_U4 = new translator_mul_mudEe<1,1,12,10,22>("translator_mul_mudEe_U4");
    translator_mul_mudEe_U4->din0(mul_fu_483_p0);
    translator_mul_mudEe_U4->din1(mul_fu_483_p1);
    translator_mul_mudEe_U4->dout(mul_fu_483_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm);

    SC_METHOD(thread_ap_CS_fsm_state1);

    SC_METHOD(thread_ap_CS_fsm_state13);

    SC_METHOD(thread_ap_CS_fsm_state14);

    SC_METHOD(thread_ap_CS_fsm_state15);

    SC_METHOD(thread_ap_CS_fsm_state3);

    SC_METHOD(thread_ap_CS_fsm_state4);

    SC_METHOD(thread_ap_condition_473);
    sensitive << ( tmp_9_fu_434_p1 );

    SC_METHOD(thread_ap_condition_485);
    sensitive << ( tmp_4_reg_515 );

    SC_METHOD(thread_ap_condition_496);
    sensitive << ( tmp_7_fu_425_p1 );

    SC_METHOD(thread_ap_phi_mux_p_0_i1_phi_fu_283_p22);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( val_V_1_read_fu_166_p2 );
    sensitive << ( tmp_9_fu_434_p1 );
    sensitive << ( ap_condition_473 );

    SC_METHOD(thread_ap_phi_mux_p_0_i2_phi_fu_245_p22);
    sensitive << ( tmp_4_reg_515 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( val_V_1_read_fu_166_p2 );
    sensitive << ( ap_condition_485 );

    SC_METHOD(thread_ap_phi_mux_p_0_i_phi_fu_321_p22);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( val_V_1_read_fu_166_p2 );
    sensitive << ( tmp_7_fu_425_p1 );
    sensitive << ( ap_condition_496 );

    SC_METHOD(thread_grp_fu_356_ap_start);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_grp_fu_356_p1);
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_grp_fu_388_ap_start);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_grp_fu_388_p1);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_mul2_fu_476_p0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul2_fu_476_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext1_cast_fu_362_p1 );

    SC_METHOD(thread_mul_fu_483_p0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_mul_fu_483_p1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext1_cast_fu_362_p1 );

    SC_METHOD(thread_p_0_i1_cast_fu_461_p1);
    sensitive << ( ap_phi_mux_p_0_i1_phi_fu_283_p22 );

    SC_METHOD(thread_p_0_i2_cast_fu_456_p1);
    sensitive << ( ap_phi_mux_p_0_i2_phi_fu_245_p22 );

    SC_METHOD(thread_p_0_i_cast_fu_466_p1);
    sensitive << ( ap_phi_mux_p_0_i_phi_fu_321_p22 );

    SC_METHOD(thread_p_cast_cast_fu_448_p3);
    sensitive << ( tmp_6_reg_509 );

    SC_METHOD(thread_tmp_3_fu_393_p2);
    sensitive << ( div1_cast_reg_502 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_tmp_4_fu_403_p3);
    sensitive << ( div1_cast_reg_502 );
    sensitive << ( tmp_3_fu_393_p2 );
    sensitive << ( tmp_5_fu_398_p2 );

    SC_METHOD(thread_tmp_5_fu_398_p2);
    sensitive << ( div1_cast_reg_502 );

    SC_METHOD(thread_tmp_6_fu_383_p2);
    sensitive << ( val_V_reg_490 );
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_tmp_7_fu_425_p1);
    sensitive << ( grp_fu_356_p2 );

    SC_METHOD(thread_tmp_9_fu_434_p1);
    sensitive << ( grp_fu_388_p2 );

    SC_METHOD(thread_toDisp);
    sensitive << ( translator_transformed_i );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_toDisp_ap_vld);
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_translator_digits_address0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_digits_address1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_digits_ce0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_digits_ce1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_digits_d0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( valor_assign_2_fu_410_p1 );
    sensitive << ( valor_assign_fu_429_p1 );

    SC_METHOD(thread_translator_digits_d1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( valor_assign_3_cast_fu_420_p1 );
    sensitive << ( valor_assign_1_fu_438_p1 );

    SC_METHOD(thread_translator_digits_we0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_digits_we1);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_disp);
    sensitive << ( whichDisp );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_disp_ap_vld);
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_translator_transformed_o);
    sensitive << ( translator_transformed_i );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( val_V_1_read_fu_166_p2 );
    sensitive << ( p_cast_cast_fu_448_p3 );
    sensitive << ( p_0_i2_cast_fu_456_p1 );
    sensitive << ( p_0_i1_cast_fu_461_p1 );
    sensitive << ( p_0_i_cast_fu_466_p1 );

    SC_METHOD(thread_translator_transformed_o_ap_vld);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( val_V_1_read_fu_166_p2 );

    SC_METHOD(thread_val_V_1_read_fu_166_p2);
    sensitive << ( whichDisp );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_valor_assign_1_fu_438_p1);
    sensitive << ( grp_fu_388_p2 );

    SC_METHOD(thread_valor_assign_2_fu_410_p1);
    sensitive << ( tmp_4_fu_403_p3 );

    SC_METHOD(thread_valor_assign_3_cast_fu_420_p1);
    sensitive << ( valor_assign_3_fu_415_p2 );

    SC_METHOD(thread_valor_assign_3_fu_415_p2);
    sensitive << ( tmp_6_reg_509 );

    SC_METHOD(thread_valor_assign_fu_429_p1);
    sensitive << ( grp_fu_356_p2 );

    SC_METHOD(thread_zext1_cast_fu_362_p1);
    sensitive << ( val_V_reg_490 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_CS_fsm );

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "translator_transform_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, number, "(port)number");
    sc_trace(mVcdFile, whichDisp, "(port)whichDisp");
    sc_trace(mVcdFile, toDisp, "(port)toDisp");
    sc_trace(mVcdFile, toDisp_ap_vld, "(port)toDisp_ap_vld");
    sc_trace(mVcdFile, translator_disp, "(port)translator_disp");
    sc_trace(mVcdFile, translator_disp_ap_vld, "(port)translator_disp_ap_vld");
    sc_trace(mVcdFile, translator_digits_address0, "(port)translator_digits_address0");
    sc_trace(mVcdFile, translator_digits_ce0, "(port)translator_digits_ce0");
    sc_trace(mVcdFile, translator_digits_we0, "(port)translator_digits_we0");
    sc_trace(mVcdFile, translator_digits_d0, "(port)translator_digits_d0");
    sc_trace(mVcdFile, translator_digits_address1, "(port)translator_digits_address1");
    sc_trace(mVcdFile, translator_digits_ce1, "(port)translator_digits_ce1");
    sc_trace(mVcdFile, translator_digits_we1, "(port)translator_digits_we1");
    sc_trace(mVcdFile, translator_digits_d1, "(port)translator_digits_d1");
    sc_trace(mVcdFile, translator_transformed_i, "(port)translator_transformed_i");
    sc_trace(mVcdFile, translator_transformed_o, "(port)translator_transformed_o");
    sc_trace(mVcdFile, translator_transformed_o_ap_vld, "(port)translator_transformed_o_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, val_V_reg_490, "val_V_reg_490");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, div_cast_reg_497, "div_cast_reg_497");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, div1_cast_reg_502, "div1_cast_reg_502");
    sc_trace(mVcdFile, tmp_6_fu_383_p2, "tmp_6_fu_383_p2");
    sc_trace(mVcdFile, tmp_6_reg_509, "tmp_6_reg_509");
    sc_trace(mVcdFile, tmp_4_fu_403_p3, "tmp_4_fu_403_p3");
    sc_trace(mVcdFile, tmp_4_reg_515, "tmp_4_reg_515");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_phi_mux_p_0_i2_phi_fu_245_p22, "ap_phi_mux_p_0_i2_phi_fu_245_p22");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, val_V_1_read_fu_166_p2, "val_V_1_read_fu_166_p2");
    sc_trace(mVcdFile, ap_phi_mux_p_0_i1_phi_fu_283_p22, "ap_phi_mux_p_0_i1_phi_fu_283_p22");
    sc_trace(mVcdFile, tmp_9_fu_434_p1, "tmp_9_fu_434_p1");
    sc_trace(mVcdFile, ap_phi_mux_p_0_i_phi_fu_321_p22, "ap_phi_mux_p_0_i_phi_fu_321_p22");
    sc_trace(mVcdFile, tmp_7_fu_425_p1, "tmp_7_fu_425_p1");
    sc_trace(mVcdFile, p_cast_cast_fu_448_p3, "p_cast_cast_fu_448_p3");
    sc_trace(mVcdFile, p_0_i2_cast_fu_456_p1, "p_0_i2_cast_fu_456_p1");
    sc_trace(mVcdFile, p_0_i1_cast_fu_461_p1, "p_0_i1_cast_fu_461_p1");
    sc_trace(mVcdFile, p_0_i_cast_fu_466_p1, "p_0_i_cast_fu_466_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, valor_assign_2_fu_410_p1, "valor_assign_2_fu_410_p1");
    sc_trace(mVcdFile, valor_assign_3_cast_fu_420_p1, "valor_assign_3_cast_fu_420_p1");
    sc_trace(mVcdFile, valor_assign_fu_429_p1, "valor_assign_fu_429_p1");
    sc_trace(mVcdFile, valor_assign_1_fu_438_p1, "valor_assign_1_fu_438_p1");
    sc_trace(mVcdFile, grp_fu_356_p1, "grp_fu_356_p1");
    sc_trace(mVcdFile, mul2_fu_476_p2, "mul2_fu_476_p2");
    sc_trace(mVcdFile, mul_fu_483_p2, "mul_fu_483_p2");
    sc_trace(mVcdFile, grp_fu_388_p1, "grp_fu_388_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_3_fu_393_p2, "tmp_3_fu_393_p2");
    sc_trace(mVcdFile, tmp_5_fu_398_p2, "tmp_5_fu_398_p2");
    sc_trace(mVcdFile, valor_assign_3_fu_415_p2, "valor_assign_3_fu_415_p2");
    sc_trace(mVcdFile, grp_fu_356_p2, "grp_fu_356_p2");
    sc_trace(mVcdFile, grp_fu_388_p2, "grp_fu_388_p2");
    sc_trace(mVcdFile, mul2_fu_476_p0, "mul2_fu_476_p0");
    sc_trace(mVcdFile, mul2_fu_476_p1, "mul2_fu_476_p1");
    sc_trace(mVcdFile, zext1_cast_fu_362_p1, "zext1_cast_fu_362_p1");
    sc_trace(mVcdFile, mul_fu_483_p0, "mul_fu_483_p0");
    sc_trace(mVcdFile, mul_fu_483_p1, "mul_fu_483_p1");
    sc_trace(mVcdFile, grp_fu_356_ap_start, "grp_fu_356_ap_start");
    sc_trace(mVcdFile, grp_fu_356_ap_done, "grp_fu_356_ap_done");
    sc_trace(mVcdFile, grp_fu_388_ap_start, "grp_fu_388_ap_start");
    sc_trace(mVcdFile, grp_fu_388_ap_done, "grp_fu_388_ap_done");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_condition_473, "ap_condition_473");
    sc_trace(mVcdFile, ap_condition_485, "ap_condition_485");
    sc_trace(mVcdFile, ap_condition_496, "ap_condition_496");
#endif

    }
}

translator_transform::~translator_transform() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete translator_urem_1bkb_U1;
    delete translator_urem_7cud_U2;
    delete translator_mul_mudEe_U3;
    delete translator_mul_mudEe_U4;
}

void translator_transform::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void translator_transform::thread_ap_clk_no_reset_() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        div1_cast_reg_502 = mul_fu_483_p2.read().range(20, 17);
        div_cast_reg_497 = mul2_fu_476_p2.read().range(20, 14);
        tmp_6_reg_509 = tmp_6_fu_383_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        tmp_4_reg_515 = tmp_4_fu_403_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        val_V_reg_490 = number.read();
    }
}

void translator_transform::thread_ap_CS_fsm() {
    ap_CS_fsm = ap_ST_fsm_state1;
}

void translator_transform::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_ST_fsm_state1[0];
}

void translator_transform::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_ST_fsm_state1[12];
}

void translator_transform::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_ST_fsm_state1[13];
}

void translator_transform::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_ST_fsm_state1[14];
}

void translator_transform::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_ST_fsm_state1[2];
}

void translator_transform::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_ST_fsm_state1[3];
}

void translator_transform::thread_ap_condition_473() {
    ap_condition_473 = (!esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_0) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_1) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_2) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_3) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_4) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_5) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_6) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_7) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_8) && !esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_9));
}

void translator_transform::thread_ap_condition_485() {
    ap_condition_485 = (!esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_0) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_1) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_2) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_3) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_4) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_5) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_6) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_7) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_8) && !esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_9));
}

void translator_transform::thread_ap_condition_496() {
    ap_condition_496 = (!esl_seteq<1,5,5>(ap_const_lv5_0, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_1, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_2, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_3, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_4, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_5, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_6, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_7, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_8, tmp_7_fu_425_p1.read()) && !esl_seteq<1,5,5>(ap_const_lv5_9, tmp_7_fu_425_p1.read()));
}

void translator_transform::thread_ap_phi_mux_p_0_i1_phi_fu_283_p22() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_B))) {
        if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_0)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_1;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_1)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_4F;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_2)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_12;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_3)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_6;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_4)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_4C;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_5)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_24;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_6)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_20;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_7)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_F;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_8)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_0;
        } else if (esl_seteq<1,5,5>(tmp_9_fu_434_p1.read(), ap_const_lv5_9)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_4;
        } else if (esl_seteq<1,1,1>(ap_condition_473.read(), ap_const_boolean_1)) {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = ap_const_lv7_7F;
        } else {
            ap_phi_mux_p_0_i1_phi_fu_283_p22 = "XXXXXXX";
        }
    } else {
        ap_phi_mux_p_0_i1_phi_fu_283_p22 = "XXXXXXX";
    }
}

void translator_transform::thread_ap_phi_mux_p_0_i2_phi_fu_245_p22() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_D))) {
        if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_0)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_1;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_1)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_4F;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_2)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_12;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_3)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_6;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_4)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_4C;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_5)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_24;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_6)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_20;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_7)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_F;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_8)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_0;
        } else if (esl_seteq<1,4,4>(tmp_4_reg_515.read(), ap_const_lv4_9)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_4;
        } else if (esl_seteq<1,1,1>(ap_condition_485.read(), ap_const_boolean_1)) {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = ap_const_lv7_7F;
        } else {
            ap_phi_mux_p_0_i2_phi_fu_245_p22 = "XXXXXXX";
        }
    } else {
        ap_phi_mux_p_0_i2_phi_fu_245_p22 = "XXXXXXX";
    }
}

void translator_transform::thread_ap_phi_mux_p_0_i_phi_fu_321_p22() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_7))) {
        if (esl_seteq<1,5,5>(ap_const_lv5_0, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_1;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_1, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_4F;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_2, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_12;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_3, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_6;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_4, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_4C;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_5, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_24;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_6, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_20;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_7, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_F;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_8, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_0;
        } else if (esl_seteq<1,5,5>(ap_const_lv5_9, tmp_7_fu_425_p1.read())) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_4;
        } else if (esl_seteq<1,1,1>(ap_condition_496.read(), ap_const_boolean_1)) {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = ap_const_lv7_7F;
        } else {
            ap_phi_mux_p_0_i_phi_fu_321_p22 = "XXXXXXX";
        }
    } else {
        ap_phi_mux_p_0_i_phi_fu_321_p22 = "XXXXXXX";
    }
}

void translator_transform::thread_grp_fu_356_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        grp_fu_356_ap_start = ap_const_logic_1;
    } else {
        grp_fu_356_ap_start = ap_const_logic_0;
    }
}

void translator_transform::thread_grp_fu_356_p1() {
    grp_fu_356_p1 =  (sc_lv<5>) (ap_const_lv10_A);
}

void translator_transform::thread_grp_fu_388_ap_start() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        grp_fu_388_ap_start = ap_const_logic_1;
    } else {
        grp_fu_388_ap_start = ap_const_logic_0;
    }
}

void translator_transform::thread_grp_fu_388_p1() {
    grp_fu_388_p1 =  (sc_lv<5>) (ap_const_lv7_A);
}

void translator_transform::thread_mul2_fu_476_p0() {
    mul2_fu_476_p0 =  (sc_lv<12>) (ap_const_lv22_667);
}

void translator_transform::thread_mul2_fu_476_p1() {
    mul2_fu_476_p1 =  (sc_lv<10>) (zext1_cast_fu_362_p1.read());
}

void translator_transform::thread_mul_fu_483_p0() {
    mul_fu_483_p0 =  (sc_lv<12>) (ap_const_lv22_51F);
}

void translator_transform::thread_mul_fu_483_p1() {
    mul_fu_483_p1 =  (sc_lv<10>) (zext1_cast_fu_362_p1.read());
}

void translator_transform::thread_p_0_i1_cast_fu_461_p1() {
    p_0_i1_cast_fu_461_p1 = esl_zext<32,7>(ap_phi_mux_p_0_i1_phi_fu_283_p22.read());
}

void translator_transform::thread_p_0_i2_cast_fu_456_p1() {
    p_0_i2_cast_fu_456_p1 = esl_zext<32,7>(ap_phi_mux_p_0_i2_phi_fu_245_p22.read());
}

void translator_transform::thread_p_0_i_cast_fu_466_p1() {
    p_0_i_cast_fu_466_p1 = esl_zext<32,7>(ap_phi_mux_p_0_i_phi_fu_321_p22.read());
}

void translator_transform::thread_p_cast_cast_fu_448_p3() {
    p_cast_cast_fu_448_p3 = (!tmp_6_reg_509.read()[0].is_01())? sc_lv<32>(): ((tmp_6_reg_509.read()[0].to_bool())? ap_const_lv32_1: ap_const_lv32_4F);
}

void translator_transform::thread_tmp_3_fu_393_p2() {
    tmp_3_fu_393_p2 = (!div1_cast_reg_502.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): (sc_biguint<4>(div1_cast_reg_502.read()) < sc_biguint<4>(ap_const_lv4_A));
}

void translator_transform::thread_tmp_4_fu_403_p3() {
    tmp_4_fu_403_p3 = (!tmp_3_fu_393_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_3_fu_393_p2.read()[0].to_bool())? div1_cast_reg_502.read(): tmp_5_fu_398_p2.read());
}

void translator_transform::thread_tmp_5_fu_398_p2() {
    tmp_5_fu_398_p2 = (!ap_const_lv4_6.is_01() || !div1_cast_reg_502.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_6) + sc_biguint<4>(div1_cast_reg_502.read()));
}

void translator_transform::thread_tmp_6_fu_383_p2() {
    tmp_6_fu_383_p2 = (!val_V_reg_490.read().is_01() || !ap_const_lv10_3E8.is_01())? sc_lv<1>(): (sc_biguint<10>(val_V_reg_490.read()) < sc_biguint<10>(ap_const_lv10_3E8));
}

void translator_transform::thread_tmp_7_fu_425_p1() {
    tmp_7_fu_425_p1 = grp_fu_356_p2.read().range(5-1, 0);
}

void translator_transform::thread_tmp_9_fu_434_p1() {
    tmp_9_fu_434_p1 = grp_fu_388_p2.read().range(5-1, 0);
}

void translator_transform::thread_toDisp() {
    toDisp = translator_transformed_i.read().range(7-1, 0);
}

void translator_transform::thread_toDisp_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        toDisp_ap_vld = ap_const_logic_1;
    } else {
        toDisp_ap_vld = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_digits_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        translator_digits_address0 =  (sc_lv<2>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        translator_digits_address0 =  (sc_lv<2>) (ap_const_lv64_2);
    } else {
        translator_digits_address0 =  (sc_lv<2>) ("XX");
    }
}

void translator_transform::thread_translator_digits_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        translator_digits_address1 =  (sc_lv<2>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        translator_digits_address1 =  (sc_lv<2>) (ap_const_lv64_3);
    } else {
        translator_digits_address1 =  (sc_lv<2>) ("XX");
    }
}

void translator_transform::thread_translator_digits_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        translator_digits_ce0 = ap_const_logic_1;
    } else {
        translator_digits_ce0 = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_digits_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        translator_digits_ce1 = ap_const_logic_1;
    } else {
        translator_digits_ce1 = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_digits_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        translator_digits_d0 = valor_assign_fu_429_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        translator_digits_d0 = valor_assign_2_fu_410_p1.read();
    } else {
        translator_digits_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void translator_transform::thread_translator_digits_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        translator_digits_d1 = valor_assign_1_fu_438_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        translator_digits_d1 = valor_assign_3_cast_fu_420_p1.read();
    } else {
        translator_digits_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void translator_transform::thread_translator_digits_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        translator_digits_we0 = ap_const_logic_1;
    } else {
        translator_digits_we0 = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_digits_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        translator_digits_we1 = ap_const_logic_1;
    } else {
        translator_digits_we1 = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_disp() {
    translator_disp = esl_zext<32,4>(whichDisp.read());
}

void translator_transform::thread_translator_disp_ap_vld() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        translator_disp_ap_vld = ap_const_logic_1;
    } else {
        translator_disp_ap_vld = ap_const_logic_0;
    }
}

void translator_transform::thread_translator_transformed_o() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        if (esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_7)) {
            translator_transformed_o = p_0_i_cast_fu_466_p1.read();
        } else if (esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_B)) {
            translator_transformed_o = p_0_i1_cast_fu_461_p1.read();
        } else if (esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_D)) {
            translator_transformed_o = p_0_i2_cast_fu_456_p1.read();
        } else if (esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_E)) {
            translator_transformed_o = p_cast_cast_fu_448_p3.read();
        } else {
            translator_transformed_o = translator_transformed_i.read();
        }
    } else {
        translator_transformed_o = translator_transformed_i.read();
    }
}

void translator_transform::thread_translator_transformed_o_ap_vld() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_E)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_D)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_B)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
          esl_seteq<1,4,4>(val_V_1_read_fu_166_p2.read(), ap_const_lv4_7)))) {
        translator_transformed_o_ap_vld = ap_const_logic_1;
    } else {
        translator_transformed_o_ap_vld = ap_const_logic_0;
    }
}

void translator_transform::thread_val_V_1_read_fu_166_p2() {
    val_V_1_read_fu_166_p2 = whichDisp.read();
}

void translator_transform::thread_valor_assign_1_fu_438_p1() {
    valor_assign_1_fu_438_p1 = esl_zext<32,7>(grp_fu_388_p2.read());
}

void translator_transform::thread_valor_assign_2_fu_410_p1() {
    valor_assign_2_fu_410_p1 = esl_zext<32,4>(tmp_4_fu_403_p3.read());
}

void translator_transform::thread_valor_assign_3_cast_fu_420_p1() {
    valor_assign_3_cast_fu_420_p1 = esl_zext<32,1>(valor_assign_3_fu_415_p2.read());
}

void translator_transform::thread_valor_assign_3_fu_415_p2() {
    valor_assign_3_fu_415_p2 = (tmp_6_reg_509.read() ^ ap_const_lv1_1);
}

void translator_transform::thread_valor_assign_fu_429_p1() {
    valor_assign_fu_429_p1 = esl_zext<32,10>(grp_fu_356_p2.read());
}

void translator_transform::thread_zext1_cast_fu_362_p1() {
    zext1_cast_fu_362_p1 = esl_zext<22,10>(val_V_reg_490.read());
}

void translator_transform::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

