// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _translator_transform_HH_
#define _translator_transform_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "translator_urem_1bkb.h"
#include "translator_urem_7cud.h"
#include "translator_mul_mudEe.h"

namespace ap_rtl {

struct translator_transform : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_lv<10> > number;
    sc_in< sc_lv<4> > whichDisp;
    sc_out< sc_lv<7> > toDisp;
    sc_out< sc_logic > toDisp_ap_vld;
    sc_out< sc_lv<32> > translator_disp;
    sc_out< sc_logic > translator_disp_ap_vld;
    sc_out< sc_lv<2> > translator_digits_address0;
    sc_out< sc_logic > translator_digits_ce0;
    sc_out< sc_logic > translator_digits_we0;
    sc_out< sc_lv<32> > translator_digits_d0;
    sc_out< sc_lv<2> > translator_digits_address1;
    sc_out< sc_logic > translator_digits_ce1;
    sc_out< sc_logic > translator_digits_we1;
    sc_out< sc_lv<32> > translator_digits_d1;
    sc_in< sc_lv<32> > translator_transformed_i;
    sc_out< sc_lv<32> > translator_transformed_o;
    sc_out< sc_logic > translator_transformed_o_ap_vld;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    translator_transform(sc_module_name name);
    SC_HAS_PROCESS(translator_transform);

    ~translator_transform();

    sc_trace_file* mVcdFile;

    translator_urem_1bkb<1,14,10,5,10>* translator_urem_1bkb_U1;
    translator_urem_7cud<1,11,7,5,7>* translator_urem_7cud_U2;
    translator_mul_mudEe<1,1,12,10,22>* translator_mul_mudEe_U3;
    translator_mul_mudEe<1,1,12,10,22>* translator_mul_mudEe_U4;
    sc_signal< sc_lv<10> > val_V_reg_490;
    sc_signal< sc_lv<15> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<7> > div_cast_reg_497;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > div1_cast_reg_502;
    sc_signal< sc_lv<1> > tmp_6_fu_383_p2;
    sc_signal< sc_lv<1> > tmp_6_reg_509;
    sc_signal< sc_lv<4> > tmp_4_fu_403_p3;
    sc_signal< sc_lv<4> > tmp_4_reg_515;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<7> > ap_phi_mux_p_0_i2_phi_fu_245_p22;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<4> > val_V_1_read_fu_166_p2;
    sc_signal< sc_lv<7> > ap_phi_mux_p_0_i1_phi_fu_283_p22;
    sc_signal< sc_lv<5> > tmp_9_fu_434_p1;
    sc_signal< sc_lv<7> > ap_phi_mux_p_0_i_phi_fu_321_p22;
    sc_signal< sc_lv<5> > tmp_7_fu_425_p1;
    sc_signal< sc_lv<32> > p_cast_cast_fu_448_p3;
    sc_signal< sc_lv<32> > p_0_i2_cast_fu_456_p1;
    sc_signal< sc_lv<32> > p_0_i1_cast_fu_461_p1;
    sc_signal< sc_lv<32> > p_0_i_cast_fu_466_p1;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<32> > valor_assign_2_fu_410_p1;
    sc_signal< sc_lv<32> > valor_assign_3_cast_fu_420_p1;
    sc_signal< sc_lv<32> > valor_assign_fu_429_p1;
    sc_signal< sc_lv<32> > valor_assign_1_fu_438_p1;
    sc_signal< sc_lv<5> > grp_fu_356_p1;
    sc_signal< sc_lv<22> > mul2_fu_476_p2;
    sc_signal< sc_lv<22> > mul_fu_483_p2;
    sc_signal< sc_lv<5> > grp_fu_388_p1;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > tmp_3_fu_393_p2;
    sc_signal< sc_lv<4> > tmp_5_fu_398_p2;
    sc_signal< sc_lv<1> > valor_assign_3_fu_415_p2;
    sc_signal< sc_lv<10> > grp_fu_356_p2;
    sc_signal< sc_lv<7> > grp_fu_388_p2;
    sc_signal< sc_lv<12> > mul2_fu_476_p0;
    sc_signal< sc_lv<10> > mul2_fu_476_p1;
    sc_signal< sc_lv<22> > zext1_cast_fu_362_p1;
    sc_signal< sc_lv<12> > mul_fu_483_p0;
    sc_signal< sc_lv<10> > mul_fu_483_p1;
    sc_signal< sc_logic > grp_fu_356_ap_start;
    sc_signal< sc_logic > grp_fu_356_ap_done;
    sc_signal< sc_logic > grp_fu_388_ap_start;
    sc_signal< sc_logic > grp_fu_388_ap_done;
    sc_signal< sc_lv<15> > ap_NS_fsm;
    sc_signal< bool > ap_condition_473;
    sc_signal< bool > ap_condition_485;
    sc_signal< bool > ap_condition_496;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<15> ap_ST_fsm_state1;
    static const sc_lv<15> ap_ST_fsm_state2;
    static const sc_lv<15> ap_ST_fsm_state3;
    static const sc_lv<15> ap_ST_fsm_state4;
    static const sc_lv<15> ap_ST_fsm_state5;
    static const sc_lv<15> ap_ST_fsm_state6;
    static const sc_lv<15> ap_ST_fsm_state7;
    static const sc_lv<15> ap_ST_fsm_state8;
    static const sc_lv<15> ap_ST_fsm_state9;
    static const sc_lv<15> ap_ST_fsm_state10;
    static const sc_lv<15> ap_ST_fsm_state11;
    static const sc_lv<15> ap_ST_fsm_state12;
    static const sc_lv<15> ap_ST_fsm_state13;
    static const sc_lv<15> ap_ST_fsm_state14;
    static const sc_lv<15> ap_ST_fsm_state15;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<7> ap_const_lv7_7F;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<4> ap_const_lv4_D;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<4> ap_const_lv4_6;
    static const sc_lv<4> ap_const_lv4_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_9;
    static const sc_lv<7> ap_const_lv7_4;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<7> ap_const_lv7_F;
    static const sc_lv<7> ap_const_lv7_20;
    static const sc_lv<7> ap_const_lv7_24;
    static const sc_lv<7> ap_const_lv7_4C;
    static const sc_lv<7> ap_const_lv7_6;
    static const sc_lv<7> ap_const_lv7_12;
    static const sc_lv<7> ap_const_lv7_4F;
    static const sc_lv<7> ap_const_lv7_1;
    static const sc_lv<4> ap_const_lv4_B;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<5> ap_const_lv5_2;
    static const sc_lv<5> ap_const_lv5_3;
    static const sc_lv<5> ap_const_lv5_4;
    static const sc_lv<5> ap_const_lv5_5;
    static const sc_lv<5> ap_const_lv5_6;
    static const sc_lv<5> ap_const_lv5_7;
    static const sc_lv<5> ap_const_lv5_8;
    static const sc_lv<5> ap_const_lv5_9;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<4> ap_const_lv4_E;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<10> ap_const_lv10_A;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<10> ap_const_lv10_3E8;
    static const sc_lv<7> ap_const_lv7_A;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<4> ap_const_lv4_A;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4F;
    static const sc_lv<22> ap_const_lv22_667;
    static const sc_lv<22> ap_const_lv22_51F;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_condition_473();
    void thread_ap_condition_485();
    void thread_ap_condition_496();
    void thread_ap_phi_mux_p_0_i1_phi_fu_283_p22();
    void thread_ap_phi_mux_p_0_i2_phi_fu_245_p22();
    void thread_ap_phi_mux_p_0_i_phi_fu_321_p22();
    void thread_grp_fu_356_ap_start();
    void thread_grp_fu_356_p1();
    void thread_grp_fu_388_ap_start();
    void thread_grp_fu_388_p1();
    void thread_mul2_fu_476_p0();
    void thread_mul2_fu_476_p1();
    void thread_mul_fu_483_p0();
    void thread_mul_fu_483_p1();
    void thread_p_0_i1_cast_fu_461_p1();
    void thread_p_0_i2_cast_fu_456_p1();
    void thread_p_0_i_cast_fu_466_p1();
    void thread_p_cast_cast_fu_448_p3();
    void thread_tmp_3_fu_393_p2();
    void thread_tmp_4_fu_403_p3();
    void thread_tmp_5_fu_398_p2();
    void thread_tmp_6_fu_383_p2();
    void thread_tmp_7_fu_425_p1();
    void thread_tmp_9_fu_434_p1();
    void thread_toDisp();
    void thread_toDisp_ap_vld();
    void thread_translator_digits_address0();
    void thread_translator_digits_address1();
    void thread_translator_digits_ce0();
    void thread_translator_digits_ce1();
    void thread_translator_digits_d0();
    void thread_translator_digits_d1();
    void thread_translator_digits_we0();
    void thread_translator_digits_we1();
    void thread_translator_disp();
    void thread_translator_disp_ap_vld();
    void thread_translator_transformed_o();
    void thread_translator_transformed_o_ap_vld();
    void thread_val_V_1_read_fu_166_p2();
    void thread_valor_assign_1_fu_438_p1();
    void thread_valor_assign_2_fu_410_p1();
    void thread_valor_assign_3_cast_fu_420_p1();
    void thread_valor_assign_3_fu_415_p2();
    void thread_valor_assign_fu_429_p1();
    void thread_zext1_cast_fu_362_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
