// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _translator_HH_
#define _translator_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "translator_transform.h"
#include "translator_transleOg.h"

namespace ap_rtl {

struct translator : public sc_module {
    // Port declarations 5
    sc_in< sc_lv<10> > number;
    sc_in< sc_lv<4> > whichDisp;
    sc_out< sc_lv<7> > toDisp;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    // Internal clock declarations for combination SystemC design. 
    sc_clock ap_sc_inter_clock;


    // Module declarations
    translator(sc_module_name name);
    SC_HAS_PROCESS(translator);

    ~translator();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    translator_transleOg* translator_digits_U;
    translator_transform* grp_translator_transform_fu_48;
    sc_signal< sc_lv<1> > translator_ssdm_t_load_fu_66_p1;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_lv<7> > grp_translator_transform_fu_48_toDisp;
    sc_signal< sc_logic > grp_translator_transform_fu_48_toDisp_ap_vld;
    sc_signal< sc_lv<32> > grp_translator_transform_fu_48_translator_disp;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_disp_ap_vld;
    sc_signal< sc_lv<2> > grp_translator_transform_fu_48_translator_digits_address0;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_digits_ce0;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_digits_we0;
    sc_signal< sc_lv<32> > grp_translator_transform_fu_48_translator_digits_d0;
    sc_signal< sc_lv<2> > grp_translator_transform_fu_48_translator_digits_address1;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_digits_ce1;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_digits_we1;
    sc_signal< sc_lv<32> > grp_translator_transform_fu_48_translator_digits_d1;
    sc_signal< sc_lv<32> > grp_translator_transform_fu_48_translator_transformed_o;
    sc_signal< sc_logic > grp_translator_transform_fu_48_translator_transformed_o_ap_vld;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<32> > translator_transformed;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_toDisp();
    void thread_translator_transformed();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_translator_ssdm_t_load_fu_66_p1();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
