# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2017.3
# Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================


/opt/Xilinx/Vivado/2017.3/../../Vivado/2017.3/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7a200tfbg676-2 ../xilinx_com_hls_ula_new_1_0.zip
