// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module ula_new_opUla (
        A,
        B,
        op,
        C,
        C_ap_vld
);


input  [15:0] A;
input  [15:0] B;
input  [2:0] op;
output  [15:0] C;
output   C_ap_vld;

wire   [15:0] aux_V_3_fu_104_p2;
reg   [15:0] ap_phi_mux_v_V_phi_fu_88_p12;
wire   [2:0] val_V_read_fu_60_p2;
wire   [15:0] p_s_fu_117_p1;
wire  signed [15:0] aux_V_2_fu_136_p2;
wire   [15:0] aux_V_1_fu_122_p2;
wire   [15:0] aux_V_fu_129_p2;
wire   [0:0] tmp_2_fu_111_p2;

ula_new_mul_mul_1bkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
ula_new_mul_mul_1bkb_U1(
    .din0(B),
    .din1(A),
    .dout(aux_V_2_fu_136_p2)
);

assign C_ap_vld = 1'b1;

always @ (*) begin
    if ((~(val_V_read_fu_60_p2 == 3'd1) & ~(val_V_read_fu_60_p2 == 3'd2) & ~(val_V_read_fu_60_p2 == 3'd3) & ~(val_V_read_fu_60_p2 == 3'd4) & ~(val_V_read_fu_60_p2 == 3'd5))) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = 16'd0;
    end else if ((val_V_read_fu_60_p2 == 3'd1)) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = aux_V_fu_129_p2;
    end else if ((val_V_read_fu_60_p2 == 3'd2)) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = aux_V_1_fu_122_p2;
    end else if ((val_V_read_fu_60_p2 == 3'd3)) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = aux_V_2_fu_136_p2;
    end else if ((val_V_read_fu_60_p2 == 3'd4)) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = p_s_fu_117_p1;
    end else if ((val_V_read_fu_60_p2 == 3'd5)) begin
        ap_phi_mux_v_V_phi_fu_88_p12 = aux_V_3_fu_104_p2;
    end else begin
        ap_phi_mux_v_V_phi_fu_88_p12 = 'bx;
    end
end

assign C = ap_phi_mux_v_V_phi_fu_88_p12;

assign aux_V_1_fu_122_p2 = (A - B);

assign aux_V_3_fu_104_p2 = (B & A);

assign aux_V_fu_129_p2 = (B + A);

assign p_s_fu_117_p1 = tmp_2_fu_111_p2;

assign tmp_2_fu_111_p2 = (($signed(A) > $signed(B)) ? 1'b1 : 1'b0);

assign val_V_read_fu_60_p2 = op;

endmodule //ula_new_opUla
