// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _simple_counter_HH_
#define _simple_counter_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "simple_counter_counting.h"

namespace ap_rtl {

struct simple_counter : public sc_module {
    // Port declarations 4
    sc_in< sc_logic > start;
    sc_in_clk clk;
    sc_in< sc_logic > reset;
    sc_out< sc_lv<10> > count_out;


    // Module declarations
    simple_counter(sc_module_name name);
    SC_HAS_PROCESS(simple_counter);

    ~simple_counter();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    simple_counter_counting* grp_simple_counter_counting_fu_48;
    sc_signal< sc_lv<10> > grp_simple_counter_counting_fu_48_count_out;
    sc_signal< sc_logic > grp_simple_counter_counting_fu_48_count_out_ap_vld;
    sc_signal< sc_lv<10> > grp_simple_counter_counting_fu_48_simple_counter_aux_V;
    sc_signal< sc_logic > grp_simple_counter_counting_fu_48_simple_counter_aux_V_ap_vld;
    sc_signal< sc_lv<2> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_count_out();
    void thread_ap_CS_fsm();
    void thread_ap_CS_fsm_state2();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
