// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="ula_new,hls_ip_2017_3,{HLS_INPUT_TYPE=sc,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a200tfbg676-2,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.225250,HLS_SYN_LAT=0,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=0,HLS_SYN_LUT=50}" *)

module ula_new (
        A,
        B,
        carryIn,
        op,
        C,
        carryOut
);


input   A;
input   B;
input   carryIn;
input  [1:0] op;
output   C;
output   carryOut;

wire    StgValue_11_ula_new_opUla_fu_50_C;
wire    StgValue_11_ula_new_opUla_fu_50_C_ap_vld;
wire    StgValue_11_ula_new_opUla_fu_50_carryOut;
wire    StgValue_11_ula_new_opUla_fu_50_carryOut_ap_vld;
wire   [0:0] ula_new_ssdm_thre_load_fu_66_p1;

ula_new_opUla StgValue_11_ula_new_opUla_fu_50(
    .A(A),
    .B(B),
    .op(op),
    .C(StgValue_11_ula_new_opUla_fu_50_C),
    .C_ap_vld(StgValue_11_ula_new_opUla_fu_50_C_ap_vld),
    .carryOut(StgValue_11_ula_new_opUla_fu_50_carryOut),
    .carryOut_ap_vld(StgValue_11_ula_new_opUla_fu_50_carryOut_ap_vld)
);

assign C = StgValue_11_ula_new_opUla_fu_50_C;

assign carryOut = StgValue_11_ula_new_opUla_fu_50_carryOut;

assign ula_new_ssdm_thre_load_fu_66_p1 = 1'd0;

endmodule //ula_new
